Configuration tabs within "Machine Setup" panel now with title
Changed for available camera objects but with some remarks:
- ImageCamera, IPCamera, OpenCVCamera, SimulatedUpCamera and Webcams
work fine
-Webcams give however a warning in the log file
log4j:WARN No appenders could be found for logger
(com.github.sarxos.webcam.Webcam).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for
more info.

- Lticivil cam give, when trying to add on the cameras panel:
Caused by: com.lti.civil.CaptureException:
java.lang.UnsatisfiedLinkError: no civil in java.library.path

-Vfw cam gives, when selecting in the machine setup tree and also after
returning to Cameras panel and selecting it:
The vonnieda.org Java video capture kit is unable to load it's native
layer.
Please make sure you have org_vonnieda_vfw_CaptureDevice.dll in
yourPATH, Windows directory or current directory.
If you do not have this file, you should be able to find the latest
version at http://www.vonnieda.org/software.html.
Load failed due to:
java.lang.UnsatisfiedLinkError: no org_vonnieda_vfw_CaptureDevice in
java.library.path
camera’s are not updated to the machine setup tree, you have to reload
and crashes the app.

The remarks however, I cannot relate to the changes made. Hence still a
commit and PR.